# Generated by Django 3.2 on 2021-05-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_auto_20210509_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='averagerating',
            name='reviews',
            field=models.ManyToManyField(blank=True, related_name='film_reviews', to='ratings.Review'),
        ),
    ]
