# Generated by Django 3.2 on 2021-05-09 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210509_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_status',
            field=models.CharField(choices=[('ENABLED', 'Активен'), ('DISABLED', 'Заблокирован')], default=None, max_length=255),
            preserve_default=False,
        ),
    ]
