# Generated by Django 3.2.2 on 2021-05-10 00:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userprofile_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='films_rated',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
