# Generated by Django 3.2.2 on 2021-05-13 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_userprofile_films_rated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='films_rated',
        ),
    ]
