# Generated by Django 3.2 on 2021-04-22 20:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128, null=True)),
                ('age', models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(150)])),
                ('works_amount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9999)])),
                ('name', models.CharField(max_length=128, unique=True)),
                ('genre', models.CharField(choices=[('ACTION', 'Экшн'), ('COMEDY', 'Комедия'), ('DRAMA', 'Драма'), ('FANTASY', 'Фантастика'), ('HORROR', 'Хоррор'), ('MYSTERY', 'Мистическое'), ('ROMANCE', 'Романтика'), ('THRILLER', 'Триллер')], max_length=128, null=True)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1850), django.core.validators.MaxValueValidator(2100)])),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(360)])),
                ('actors', models.ManyToManyField(related_name='film_actors', to='films.Celebrity')),
                ('producer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_producer', to='films.celebrity')),
            ],
        ),
    ]
