# Generated by Django 3.2.2 on 2021-05-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_alter_film_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='average_rating',
        ),
    ]
